api_config:
  groq_api_key: sk-xxx
  groq_api_url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
  groq_model: qwen-plus
  selected_api: Groq
author: UglyFeed
category: Technology
copyright: UglyFeed
enable_github: false
enable_gitlab: false
enable_tts: false
feed_description: A dynamically generated feed using UglyFeed.
feed_language: en
feed_link: https://github.com/fabriziosalmi/UglyFeed
feed_self_link: https://raw.githubusercontent.com/fabriziosalmi/UglyFeed/main/examples/uglyfeed-source-1.xml
feed_title: UglyFeed RSS
folders:
  output_folder: output
  rewritten_folder: rewritten
github_repo: luc99hen/UglyFeed.git 
github_token: your_github_token
gitlab_repo: your_gitlab_username/uglyfeed-cdn
gitlab_token: your_gitlab_token
http_server_port: 8001
input_feeds_path: input/feeds.txt
max_age_days: 10
max_items: 50
moderation:
  allow_duplicates: false
  enabled: false
  words_file: moderation/IT.txt
preprocessing:
  additional_stopwords: []
  lemmatization: false
  lowercase: false
  remove_html: true
  remove_punctuation: false
  use_stemming: false
prompt_file: prompt_EN.txt
scheduling_enabled: false
scheduling_interval: 4
scheduling_period: hours
similarity_options:
  eps: 0.5
  linkage: average
  method: dbscan
  min_samples: 2
  n_clusters: 5
similarity_threshold: 0.5
speed_factor: 1.25
tts_input: rewritten
tts_language: it
tts_output: media
vectorization:
  max_df: 0.85
  max_features: 5000
  method: tfidf
  min_df: 0.01
  ngram_range:
  - 1
  - 2
