name: Rewrite Feeds and Deploy

on:  [push]

jobs:
  rewrite-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out UglyFeed repository
      uses: actions/checkout@v3
      with:
        repository: luc99hen/UglyFeed
        ref: develop
        path: UglyFeed

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r UglyFeed/requirements.txt

    - name: Download and verify NLTK data
      run: |
        mkdir -p /home/runner/nltk_data
        python -m nltk.downloader -d /home/runner/nltk_data wordnet stopwords omw-1.4
        echo "Verifying NLTK downloads..."
        ls -la /home/runner/nltk_data/corpora
      env:
        NLTK_DATA: /home/runner/nltk_data

    - name: Override config.yaml with secrets
      run: |
        cp UglyFeed/config.yaml UglyFeed/config.yaml.bak
        yq eval '.api_config.groq_api_key = strenv(GROQ_API_KEY)' -i UglyFeed/config.yaml
        yq eval '.api_config.selected_api = strenv(SELECTED_API)' -i UglyFeed/config.yaml
        yq eval '.api_config.groq_api_url = strenv(GROQ_API_URL)' -i UglyFeed/config.yaml
        yq eval '.api_config.groq_model = strenv(GROQ_MODEL)' -i UglyFeed/config.yaml
        yq eval '.github_token = strenv(GENERATOR_TOKEN)' -i UglyFeed/config.yaml
        yq eval '.enable_github = true' -i UglyFeed/config.yaml

      env:
        SIMILARITY_THRESHOLD: ${{ vars.SIMILARITY_THRESHOLD }}
        MIN_SAMPLES: ${{ vars.MIN_SAMPLES }}
        EPS: ${{ vars.EPS }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        SELECTED_API: ${{ vars.SELECTED_API }}
        GROQ_API_URL: ${{ vars.GROQ_API_URL }}
        GROQ_MODEL: "qwen-plus"
        OUTPUT_FOLDER: ${{ github.workspace }}/UglyFeed/output
        REWRITTEN_FOLDER: ${{ github.workspace }}/UglyFeed/rewritten
        GENERATOR_TOKEN: ${{ secrets.GENERATOR_TOKEN }}

    - name: Debug config.yaml
      run: |
        echo "Contents of config.yaml after overriding with secrets:"
        cat UglyFeed/config.yaml

    - name: Run main.py
      run: |
        cd UglyFeed
        python main.py
      env:
        NLTK_DATA: /home/runner/nltk_data


    - name: Commit and push to uglyfeed-cdn
      run: |
        cd ${{ github.workspace }}/UglyFeed
        git config --local user.name "luc99hen"
        git config --local user.email "luc99.en@gmail.com"
        git add uglyfeeds/uglyfeed.xml
        git commit -m "Deploy rewritten RSS feed - $(date +'%Y-%m-%d %H:%M:%S') [Model: ${{ vars.GROQ_MODEL }}, API: ${{ vars.SELECTED_API }}]"
        git push https://x-access-token:${{ secrets.GENERATOR_TOKEN }}@github.com/luc99hen/UglyFeed.git HEAD:develop
